# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healtha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
